#!/bin/bash
alias sc='source ~/.bashrc'
alias ec='vim ~/.bashrc'
alias dc='docker container'
alias dcs='docker container start'
alias dcl='docker container logs'
alias dcls='docker container ls --all'
alias gs='git status'
alias ga='git add .'
alias gc='git commit'
alias gp='git push'
alias gpl='git pull'
alias gf='git fetch'
alias gck='git checkout -b'
alias gacp='ga && gc && gp'
